export const floorplans = [
  'https://wcs.smartdraw.com/floor-plan/img/floor-plan.png?bn=1510011154',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRmfeuPKNFAaagiLpgls9vJgtbFaFwlJameiboJA-APy4QC6u7W',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQl0lHpRTp66MZa48DT-mLqZI9kEmDv8_aTW1Wq2xjqVsjP6tVm',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTliTXR4SorDliv3jSCweEe7Qre5WJ3g39qkhv5rp-6OA2X5oae',
];

export default {
  rooms: {
    roomsData: {
      RED: {
        id: 'RED',
        price: 900,
        name: 'Red room',
        maxAdults: 2,
        maxChild: 1,
        images: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSDtceovd4FcLQPO6Qv2_bsc9amY-GeuIN7O0PPxv5eYJwHQspp',
          'https://www.hotel-negresco-nice.com/sites/default/files/styles/750x390/public/2019-07/imperiale%202-1116x583_0.jpg?h=9466075d&itok=5G4yaO-d',
        ],
        floorplan: 'https://wcs.smartdraw.com/floor-plan/img/floor-plan.png?bn=1510011154',
        facilities: [
          'Double bed', 'Balcon', 'Shower', 'Terrace', 'Air conditioning', 'Approx room size: 28 square metres',
        ],
      },
      GREEN: {
        id: 'GREEN',
        price: 1000,
        name: 'Green room',
        maxAdults: 2,
        maxChild: 1,
        images: [
          'https://img.themirahotel.com/wp-content/uploads/2015/05/CourtyardRooms_TheMiraHongKong_Luxury5StarHotel_TsimShaTsui_HongKong-1024x511.jpg',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTJpwRPO2ujAiOfn9Qs7HEP-DQNwyIxIdoae5ZJwgF0ZpbO8Ybu',
        ],
        floorplan: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRmfeuPKNFAaagiLpgls9vJgtbFaFwlJameiboJA-APy4QC6u7W',
        facilities: [
          'Double bed', 'Balcon', 'Shower', 'Terrace', 'Air conditioning', 'Approx room size: 28 square metres',
        ],
      },
      BLUE: {
        id: 'BLUE',
        price: 1200,
        name: 'Blue room',
        maxAdults: 2,
        maxChild: 1,
        images: [
          'https://pix10.agoda.net/hotelImages/3036216/-1/a629aa7817be9e0e6cbdf773f1502713.jpg?s=1024x768',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQiyEGH29RVNulGslkwtJnYBJEiSr3-Dfrs_iv6qFRpLLmr_PQ2',
        ],
        floorplan: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQl0lHpRTp66MZa48DT-mLqZI9kEmDv8_aTW1Wq2xjqVsjP6tVm',
        facilities: [
          'Double bed', 'Balcon', 'Shower', 'Terrace', 'Air conditioning', 'Approx room size: 28 square metres',
        ],
      },
      YELLOW: {
        id: 'YELLOW',
        price: 1500,
        name: 'Yellow room',
        maxAdults: 2,
        maxChild: 1,
        images: [
          'https://imgcy.trivago.com/c_limit,d_dummy.jpeg,f_auto,h_1300,q_auto,w_2000/itemimages/10/21/102157_v11.jpeg',
          'https://r-cf.bstatic.com/images/hotel/max1024x768/158/158870852.jpg',
        ],
        floorplan: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTliTXR4SorDliv3jSCweEe7Qre5WJ3g39qkhv5rp-6OA2X5oae',
        facilities: [
          'Double bed', 'Balcon', 'Shower', 'Terrace', 'Air conditioning', 'Approx room size: 28 square metres',
        ],
      },
    },
    initialRooms: [
      {
        id: 'RED',
        passengersString: '2 adults',
      },
      {
        id: 'GREEN',
        passengersString: '2 adults and 1 child',
      },
    ],
    upgradeRooms: [
      ['RED', 'BLUE', 'YELLOW', 'GREEN'],
      ['RED', 'BLUE', 'YELLOW', 'GREEN'],
    ],
  },
  availableFlights: [
    {
      code: 'FAG038',
      date: '2020-02-22',
      duration: 7,
      price: 1500,
      chosenFlight: true,
      flights: {
        depRoute: {
          code: 'GNBBHX6CBHXGNB',
          flightNo: 'LS1345',
          carrierName: 'Jet2',
          depName: 'Birmingham International',
          depDate: '2020-02-22',
          depTime: '15:30',
          depCode: 'BHX',
          arrName: 'Grenoble',
          arrDate: '2020-02-22',
          arrTime: '18:25',
          arrCode: 'GNB',
          luggageAllowance: '20kg and 1 hold bag',
        },
        retRoute: {
          code: 'GNBBHX6CGNBBHX',
          flightNo: 'LS1346',
          carrierName: 'Jet2',
          depName: 'Grenoble',
          depDate: '2020-02-29',
          depTime: '19:25',
          depCode: 'GNB',
          arrName: 'Birmingham International',
          arrDate: '2020-02-29',
          arrTime: '20:20',
          arrCode: 'BHX',
          luggageAllowance: '20kg and 1 hold bag',
        },
      },
    },
    {
      code: 'FAG039',
      date: '2020-02-22',
      duration: 7,
      price: 1600,
      chosenFlight: false,
      flights: {
        depRoute: {
          code: 'GNBBJK6CBHXGNB',
          flightNo: 'LK1345',
          carrierName: 'Jet2',
          depName: 'Birmingham International',
          depDate: '2020-02-22',
          depTime: '15:00',
          depCode: 'BHX',
          arrName: 'Grenoble',
          arrDate: '2020-02-22',
          arrTime: '17:55',
          arrCode: 'GNB',
          luggageAllowance: '20kg and 1 hold bag',
        },
        retRoute: {
          code: 'GNBBLS6CGNBBHX',
          flightNo: 'LK1346',
          carrierName: 'Jet2',
          depName: 'Grenoble',
          depDate: '2020-02-29',
          depTime: '18:55',
          depCode: 'GNB',
          arrName: 'Birmingham International',
          arrDate: '2020-02-29',
          arrTime: '19:50',
          arrCode: 'BHX',
          luggageAllowance: '20kg and 1 hold bag',
        },
      },
    },
  ],
  holiday: {
    totalPrice: 2000,
    depositAmount: 0,
    duration: 7,
    departureDate: '2020-02-22',
    withoutFlights: false,
    isWinter: true,
    isSailing: false,
    accommodationName: 'Mar Menor Beachclub',
    destinationResort: 'Los Urrutias',
    destinationRegion: 'Spain',
  },
  passengers: [
    {
      index: 1,
      age: 30,
      title: '',
      firstName: '',
      lastName: '',
      sex: '',
      room: 1,
      isAdult: true,
      isInfant: false,
    },
    {
      index: 2,
      age: 30,
      title: '',
      firstName: '',
      lastName: '',
      sex: '',
      room: 1,
      isAdult: true,
      isInfant: false,
    },
  ],
  progressBarItems: [],
  flightExtras: {
    489: {
      id: '489',
      name: 'Sports equipment',
      description: '<p>Add on special luggage for your sports equipment, prices shown are for both inbound and outbound flights.</p>',
      type: 'person',
      multiSelect: true,
      admissionType: 'all',
      showTitle: true,
      showDescription: true,
      extras: {
        SSKI: {
          name: 'Ski & Board Carriage',
          autoInclude: 'MAN',
          class: 'Y',
          Book_Mth: 'PAX',
          minAge: '2',
          maxChildAge: '',
          adultPrice: 22.5,
          childPrice: 22.5,
          flightExtraCatCode: 'OTHER',
          flightExtraCatName: 'Flight Extras',
          flightExtraCatMethod: 'OTH',
          availablity: 13,
          isFlight: true,
          code: 'SSKI',
          identifier: 'SSKI',
          neilsonName: 'Ski and board carriage',
          description: null,
          isAssignable: true,
          setKey: '489',
          count: 0,
          passengers: [],
          showWeekLabel: false,
          weight: 1,
          weekLabel: '',
          pricePerPerson: 22.5,
          maxNumber: 2,
          passengersToAssign: [],
        },
      },
      showSkiLevels: false,
    },
  },
  holidayExtras: {},
  marketingPreferences: [],
};
