export default {
  rooms: {},
  availableFlights: [
    {
      accomCode: 'FAG038',
      date: '2020-02-22',
      duration: 7,
      price: 1500,
      chosenFlight: true,
      flights: {
        depRoute: {
          code: 'GNBBHX6CBHXGNB',
          flightNo: 'LS1345',
          flightInvId: '68637016',
          carrier: 'LS',
          carrierName: 'Jet2',
          depName: 'Birmingham International',
          depDate: '2020-02-22',
          depTime: '15:30',
          arrDate: '2020-02-22',
          arrTime: '18:25',
          depCode: 'BHX',
          arrCode: 'GNB',
          promCode: 'NEL1',
          luggageAllowance: '20kg and 1 hold bag',
          logoUrl: 'http://neilson.loc:8010/sites/default/files/styles/compress_only/public/2020-01/Quake-III-Arena-icon.png?itok=050IoLMP',
        },
        retRoute: {
          code: 'GNBBHX6CGNBBHX',
          flightNo: 'LS1346',
          flightInvId: '68637374',
          carrier: 'LS',
          carrierName: 'Jet2',
          depName: 'Grenoble',
          depDate: '2020-02-29',
          depTime: '19:25',
          arrDate: '2020-02-29',
          arrTime: '20:20',
          depCode: 'GNB',
          arrCode: 'BHX',
          promCode: 'NEL1',
          luggageAllowance: '20kg and 1 hold bag',
          logoUrl: 'http://neilson.loc:8010/sites/default/files/styles/compress_only/public/2020-01/Quake-III-Arena-icon.png?itok=050IoLMP',
        },
      },
    },
  ],
  currentStep: '',
  nextStep: '',
  previousStep: '',
  holiday: {
    totalPrice: 2000,
    depositAmount: 0,
    duration: 7,
    departureDate: '2020-02-22',
    withoutFlights: false,
    isWinter: true,
    isSailing: false,
    accommodationName: 'Mar Menor Beachclub',
    destinationResort: 'Los Urrutias',
    destinationRegion: 'Spain',
  },
  passengers: [
    {
      index: 1,
      age: 30,
      firstName: '',
      lastName: '',
      sex: '',
      room: 1,
      isAdult: true,
      isInfant: false,
    },
    {
      index: 2,
      age: 30,
      firstName: '',
      lastName: '',
      sex: '',
      room: 1,
      isAdult: true,
      isInfant: false,
    },
  ],
  progressBarItems: [],
  flightExtras: {
    489: {
      id: '489',
      name: 'Sports equipment',
      description: '<p>Add on special luggage for your sports equipment, prices shown are for both inbound and outbound flights.</p>',
      type: 'person',
      multiSelect: true,
      admissionType: 'all',
      showTitle: true,
      showDescription: true,
      extras: {
        SSKI: {
          name: 'Ski & Board Carriage',
          autoInclude: 'MAN',
          class: 'Y',
          Book_Mth: 'PAX',
          minAge: '2',
          maxChildAge: '',
          adultPrice: 22.5,
          childPrice: 22.5,
          flightExtraCatCode: 'OTHER',
          flightExtraCatName: 'Flight Extras',
          flightExtraCatMethod: 'OTH',
          availablity: 13,
          isFlight: true,
          code: 'SSKI',
          identifier: 'SSKI',
          neilsonName: 'Ski and board carriage',
          description: null,
          isAssignable: true,
          setKey: '489',
          count: 0,
          passengers: [],
          showWeekLabel: false,
          weight: 1,
          weekLabel: '',
          pricePerPerson: 22.5,
          maxNumber: 2,
          passengersToAssign: [],
        },
      },
      showSkiLevels: false,
    },
  },
  holidayExtras: {},
  marketingPreferences: [],
};
