export const mockedPassengers = [
  {
    index: 1,
    title: 'Mr',
    firstName: 'John',
    lastName: 'Doe',
    birthDay: '01/01/2000',
    room: 1,
    isAdult: true,
    isInfant: false,
    isLeadPassenger: true,
  },
  {
    index: 2,
    title: 'Mrs',
    firstName: 'Julia',
    lastName: 'Ivanova',
    birthDay: '01/01/1991',
    room: 1,
    isAdult: true,
    isInfant: false,
    isLeadPassenger: false,
  },
  {
    index: 3,
    title: 'Mr',
    firstName: 'Philip',
    lastName: 'Moris',
    birthDay: '02/02/1980',
    room: 2,
    isAdult: true,
    isInfant: false,
    isLeadPassenger: false,
  },
  {
    index: 4,
    title: 'Mr',
    firstName: 'Andry',
    lastName: 'Grey',
    birthDay: '04/02/1995',
    room: 2,
    isAdult: true,
    isInfant: false,
    isLeadPassenger: false,
  },
  {
    index: 5,
    title: 'Miss',
    firstName: 'Emily',
    lastName: 'Green',
    birthDay: '01/01/2009',
    age: 10,
    room: 2,
    isAdult: false,
    isInfant: false,
    isLeadPassenger: false,
  },
];

export const mockedLeadPassengerData = {
  $invalid: false,
  $validationTrigger: false,
  contactNumber: '89235432332',
  email: 'test@mail.com',
  addressCity: 'Omsk',
  addressCountry: 'Russia',
  addressCounty: 'Omskaya obl.',
  addressLine1: 'Lenina 1',
  addressLine2: '',
  addressPostcode: '644122',
};
